# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 06:28
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Workflow = apps.get_model('document_states', 'Workflow')
    for workflow in Workflow.objects.all():
        workflow.slug = slugify(workflow.label).replace('-', '_')
        workflow.save()


class Migration(migrations.Migration):

    dependencies = [
        ('document_states', '0003_auto_20170325_0447'),
    ]

    operations = [
        # Add the slug field but make it non unique
        # https://docs.djangoproject.com/en/1.10/howto/
        # writing-migrations/#migrations-that-add-unique-fields
        migrations.AddField(
            model_name='workflow',
            name='slug',
            field=models.SlugField(
                default=' ',
                help_text='This value will be used by other apps to reference '
                'this workflow. Can only contain letters, numbers, and '
                'underscores.', max_length=255, unique=False,
                verbose_name='Slug'
            ),
        ),

        # Generate the slugs based on the labels
        migrations.RunPython(
            generate_slugs, reverse_code=migrations.RunPython.noop
        ),

        # Make the slug field unique
        migrations.AlterField(
            model_name='workflow',
            name='slug',
            field=models.SlugField(
                help_text='This value will be used by other apps to reference '
                'this workflow. Can only contain letters, numbers, and '
                'underscores.', max_length=255, unique=True,
                verbose_name='Slug'
            ),
        ),

    ]
